### YamlMime:UniversalReference
items:
  - uid: office.Visio.Application
    summary: |-
      Represents the Application.

      \[ [Api set: 1.1](http://bing.com) \]
    name: Visio.Application
    fullName: office.Visio.Application
    langs:
      - typeScript
    type: class
    extends:
      - OfficeExtension.ClientObject
    package: office
    children:
      - office.Visio.Application.load
      - office.Visio.Application.set
      - office.Visio.Application.showBorders
      - office.Visio.Application.showToolbar
      - office.Visio.Application.showToolbars
      - office.Visio.Application.toJSON
  - uid: office.Visio.Application.load
    summary: >-
      Queues up a command to load the specified properties of the object. You must call "context.sync()" before reading
      the properties.
    name: load(option)
    fullName: office.Visio.Application.load
    langs:
      - typeScript
    type: method
    syntax:
      content: 'load(option?: Visio.Interfaces.ApplicationLoadOptions): Visio.Application;'
      return:
        type:
          - Visio.Application
        description: ''
      parameters:
        - id: option
          description: ''
          type:
            - Visio.Interfaces.ApplicationLoadOptions
  - uid: office.Visio.Application.set
    summary: 'Sets multiple properties on the object at the same time, based on JSON input.'
    name: 'set(properties, options)'
    fullName: office.Visio.Application.set
    langs:
      - typeScript
    type: method
    syntax:
      content: "set(properties: Interfaces.ApplicationUpdateData, options?: {\r\n            throwOnReadOnly?: boolean;\r\n        }): void;"
      return:
        type:
          - void
        description: ''
      parameters:
        - id: properties
          description: ''
          type:
            - Interfaces.ApplicationUpdateData
        - id: options
          description: ''
          type:
            - "{\r\n            /**\r\n             * Throw an error if the passed-in property list includes read-only properties (default = true).\r\n             */\r\n            throwOnReadOnly?: boolean;\r\n        }"
  - uid: office.Visio.Application.showBorders
    summary: |-
      Show/Hide the application borders.

      \[ [Api set: 1.1](http://bing.com) \]
    name: showBorders
    fullName: office.Visio.Application.showBorders
    langs:
      - typeScript
    type: property
    syntax:
      content: 'showBorders: boolean;'
      return:
        type:
          - boolean
  - uid: office.Visio.Application.showToolbar
    summary: |-
      Show or Hide a particular toolbar.

      \[ [Api set: 1.1](http://bing.com) \]
    name: 'showToolbar(id, show)'
    fullName: office.Visio.Application.showToolbar
    langs:
      - typeScript
    type: method
    syntax:
      content: 'showToolbar(id: string, show: boolean): void;'
      return:
        type:
          - void
        description: ''
      parameters:
        - id: id
          description: ''
          type:
            - string
        - id: show
          description: ''
          type:
            - boolean
  - uid: office.Visio.Application.showToolbars
    summary: |-
      Show or Hide the standard toolbars.

      \[ [Api set: 1.1](http://bing.com) \]
    name: showToolbars
    fullName: office.Visio.Application.showToolbars
    langs:
      - typeScript
    type: property
    syntax:
      content: 'showToolbars: boolean;'
      return:
        type:
          - boolean
  - uid: office.Visio.Application.toJSON
    name: toJSON()
    fullName: office.Visio.Application.toJSON
    langs:
      - typeScript
    type: method
    syntax:
      content: 'toJSON(): Visio.Interfaces.ApplicationData;'
      return:
        type:
          - Visio.Interfaces.ApplicationData
        description: ''
