// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

/**
 * Post-processor for Office API documentation YAML files.
 *
 * This script adds Office-specific enhancements to YAML files generated by api-documenter:
 * 1. Injects code examples from snippets.yaml files
 * 2. Hyperlinks API set references with product-specific URLs
 * 3. Adds "Used By" sections showing where types are referenced in the API
 *
 * The "Used By" feature builds a reverse index from the API Extractor JSON files,
 * identifying all places where a type is used (as property types, method return types,
 * or parameter types). This helps users understand the relationships between types
 * and discover relevant APIs.
 *
 * Previously these features were implemented in a custom OfficeYamlDocumenter class
 * that extended api-documenter. This post-processing approach allows us to use the
 * standard api-documenter tool.
 */

import * as fsx from 'fs-extra';
import * as yaml from 'js-yaml';
import * as path from 'path';

// ---- Configuration ----

const YAML_BASE_PATH = path.resolve('../yaml');
const JSON_BASE_PATH = path.resolve('../json');

// All product folders to process
const PRODUCT_FOLDERS = [
  'office',
  'office_release',
  'office-runtime',
  'excel',
  'excel_1_1',
  'excel_1_2',
  'excel_1_3',
  'excel_1_4',
  'excel_1_5',
  'excel_1_6',
  'excel_1_7',
  'excel_1_8',
  'excel_1_9',
  'excel_1_10',
  'excel_1_11',
  'excel_1_12',
  'excel_1_13',
  'excel_1_14',
  'excel_1_15',
  'excel_1_16',
  'excel_1_17',
  'excel_1_18',
  'excel_1_19',
  'excel_1_20',
  'excel_online',
  'excel_desktop_1_1',
  'onenote',
  'outlook',
  'outlook_1_1',
  'outlook_1_2',
  'outlook_1_3',
  'outlook_1_4',
  'outlook_1_5',
  'outlook_1_6',
  'outlook_1_7',
  'outlook_1_8',
  'outlook_1_9',
  'outlook_1_10',
  'outlook_1_11',
  'outlook_1_12',
  'outlook_1_13',
  'outlook_1_14',
  'outlook_1_15',
  'powerpoint',
  'powerpoint_1_1',
  'powerpoint_1_2',
  'powerpoint_1_3',
  'powerpoint_1_4',
  'powerpoint_1_5',
  'powerpoint_1_6',
  'powerpoint_1_7',
  'powerpoint_1_8',
  'powerpoint_1_9',
  'powerpoint_1_10',
  'visio',
  'word',
  'word_1_1',
  'word_1_2',
  'word_1_3',
  'word_1_4',
  'word_1_5',
  'word_1_6',
  'word_1_7',
  'word_1_8',
  'word_1_9',
  'word_1_3_hidden_document',
  'word_1_4_hidden_document',
  'word_1_5_hidden_document',
  'word_desktop_1_1',
  'word_desktop_1_2',
  'word_desktop_1_3',
  'word_desktop_1_4',
  'word_online'
];

// Requirement set URL mappings
const REQUIREMENT_SET_URLS: Record<string, string> = {
  excel: '/javascript/api/requirement-sets/excel/excel-api-requirement-sets',
  word: '/javascript/api/requirement-sets/word/word-api-requirement-sets',
  outlook: '/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets',
  powerpoint: '/javascript/api/requirement-sets/powerpoint/powerpoint-api-requirement-sets',
  onenote: '/javascript/api/requirement-sets/onenote/onenote-api-requirement-sets',
  visio: '/office/dev/add-ins/reference/overview/visio-javascript-reference-overview',
  default: '/office/dev/add-ins/reference/javascript-api-for-office'
};

// ---- Interfaces ----

interface ISnippetsFile {
  [apiName: string]: string[];
}

interface IYamlItem {
  uid?: string;
  summary?: string;
  remarks?: string;
  syntax?: {
    return?: {
      description?: string;
    };
  };
}

interface UsedByReference {
  uid: string;              // Full UID of the using member (e.g., "office!Office.Context#diagnostics:member")
  name: string;             // Display name (e.g., "Office.Context.diagnostics")
  memberType: string;       // "property", "method", "parameter", etc.
  packageName: string;      // Package name (e.g., "office", "excel")
  contextText: string;      // Human-readable context (e.g., "property type")
}

interface UsedByIndex {
  [typeUID: string]: UsedByReference[];
}

interface ApiJsonMember {
  kind: string;
  canonicalReference?: string;
  name?: string;
  excerptTokens?: ApiJsonToken[];
  members?: ApiJsonMember[];
  properties?: ApiJsonMember[];
  methods?: ApiJsonMember[];
  events?: ApiJsonMember[];
  returnTypeTokenRange?: { startIndex: number; endIndex: number };
  parameters?: Array<{
    parameterName: string;
    parameterTypeTokenRange: { startIndex: number; endIndex: number };
  }>;
}

interface ApiJsonToken {
  kind: string;
  text?: string;
  canonicalReference?: string;
}

interface ApiJsonFile {
  kind?: string;
  name?: string;
  members?: ApiJsonMember[];
}

// ---- Used By Index Building ----

/**
 * Builds a reverse index mapping type UIDs to the members that use them.
 * This allows us to show "Used By" sections on type documentation pages.
 */
function buildUsedByIndex(): UsedByIndex {
  const index: UsedByIndex = {};

  // Process all JSON files for all products
  for (const folder of PRODUCT_FOLDERS) {
    const jsonPath = path.join(JSON_BASE_PATH, folder, `${getBaseProductName(folder)}.api.json`);

    if (!fsx.existsSync(jsonPath)) {
      continue;
    }

    try {
      const jsonContent = fsx.readFileSync(jsonPath, 'utf-8');
      const apiJson: ApiJsonFile = JSON.parse(jsonContent);
      const packageName = getBaseProductName(folder);

      // Analyze all members in this JSON file
      analyzeMembers(apiJson, index, packageName);
    } catch (error) {
      console.warn(`  Warning: Failed to process ${jsonPath}: ${error}`);
    }
  }

  return index;
}

/**
 * Extracts the base product name from a folder name.
 * E.g., "excel_1_5" -> "excel", "outlook" -> "outlook"
 */
function getBaseProductName(folderName: string): string {
  // Match patterns like "excel_1_5", "word_desktop_1_1", "office_release"
  const match = folderName.match(/^([a-z-]+)/);
  return match ? match[1] : folderName;
}

/**
 * Recursively analyzes all members in an API JSON structure.
 */
function analyzeMembers(container: ApiJsonMember | ApiJsonFile, index: UsedByIndex, packageName: string): void {
  if (!container) {
    return;
  }

  const members = container.members || [];

  for (const member of members) {
    if (!member.canonicalReference) {
      continue;
    }

    // Analyze this member's type references
    analyzeMemberTypeReferences(member, index, packageName);

    // Recursively analyze nested members
    analyzeMembers(member, index, packageName);
  }
}

/**
 * Analyzes a single member to extract type references from:
 * - Property types
 * - Method return types
 * - Method parameter types
 * - Function return types
 * - Function parameter types
 */
function analyzeMemberTypeReferences(member: ApiJsonMember, index: UsedByIndex, packageName: string): void {
  if (!member.excerptTokens || !member.canonicalReference) {
    return;
  }

  // For properties: analyze the property type
  // Handle both interface properties (PropertySignature) and class properties (Property)
  if (member.kind === 'PropertySignature' || member.kind === 'Property') {
    analyzeExcerptTokens(member.excerptTokens, member.canonicalReference, 'property type', index, packageName);
  }

  // For methods and functions: analyze return type and parameters
  // Handle interface methods (MethodSignature), class methods (Method), and namespace functions (Function)
  if (member.kind === 'MethodSignature' || member.kind === 'Method' || member.kind === 'Function') {
    // Return type
    if (member.returnTypeTokenRange) {
      const returnTokens = member.excerptTokens.slice(
        member.returnTypeTokenRange.startIndex,
        member.returnTypeTokenRange.endIndex
      );
      analyzeExcerptTokens(returnTokens, member.canonicalReference, 'return type', index, packageName);
    }

    // Parameters
    if (member.parameters) {
      for (const param of member.parameters) {
        const paramTokens = member.excerptTokens.slice(
          param.parameterTypeTokenRange.startIndex,
          param.parameterTypeTokenRange.endIndex
        );
        analyzeExcerptTokens(paramTokens, member.canonicalReference, 'parameter type', index, packageName);
      }
    }
  }
}

/**
 * Analyzes excerpt tokens to find type references.
 */
function analyzeExcerptTokens(
  tokens: ApiJsonToken[],
  usingMemberUID: string,
  contextText: string,
  index: UsedByIndex,
  packageName: string
): void {
  for (const token of tokens) {
    if (token.kind === 'Reference' && token.canonicalReference) {
      const referencedTypeUID = token.canonicalReference;

      // Skip built-in types (Promise, Array, etc.)
      if (referencedTypeUID.startsWith('!')) {
        continue;
      }

      // Add to index
      if (!index[referencedTypeUID]) {
        index[referencedTypeUID] = [];
      }

      // Create reference entry
      const reference: UsedByReference = {
        uid: usingMemberUID,
        name: formatDisplayName(usingMemberUID),
        memberType: getMemberType(usingMemberUID),
        packageName: packageName,
        contextText: contextText
      };

      index[referencedTypeUID].push(reference);
    }
  }
}

/**
 * Gets the member type from a UID or kind string.
 */
function getMemberType(kindOrUID: string): string {
  if (kindOrUID.includes(':member')) {
    return 'property';
  } else if (kindOrUID.includes(':method')) {
    return 'method';
  } else if (kindOrUID.includes(':function')) {
    return 'function';
  } else if (kindOrUID.includes(':interface')) {
    return 'interface';
  } else if (kindOrUID.includes(':class')) {
    return 'class';
  } else if (kindOrUID.includes(':enum')) {
    return 'enum';
  } else if (kindOrUID.includes(':type')) {
    return 'type';
  } else if (kindOrUID === 'PropertySignature') {
    return 'property';
  } else if (kindOrUID === 'MethodSignature') {
    return 'method';
  } else if (kindOrUID === 'Function') {
    return 'function';
  }
  return 'member';
}

/**
 * Formats a UID into a display name.
 * E.g., "office!Office.Context#diagnostics:member" -> "Office.Context.diagnostics"
 */
function formatDisplayName(uid: string): string {
  // Remove package prefix: "office!Office.Context#diagnostics:member" -> "Office.Context#diagnostics:member"
  const withoutPackage = uid.replace(/^[^!]+!/, '');

  // Replace # with . and remove :kind suffix
  const cleaned = withoutPackage.replace(/#/g, '.').replace(/:[a-z]+(\(\d+\))?$/, '');

  return cleaned;
}

/**
 * Injects a "Used By" section into a YAML item if there are references to it.
 * Only includes references to APIs that exist in the current package/version.
 * Also includes cross-product references between Common API and product-specific APIs.
 */
function injectUsedBySection(
  item: IYamlItem,
  usedByIndex: UsedByIndex,
  availableUIDs: Set<string>,
  commonApiUIDs: Set<string>,
  currentPackage: string
): boolean {
  if (!item.uid) {
    return false;
  }

  const references = usedByIndex[item.uid];

  if (!references || references.length === 0) {
    return false;
  }

  // Inject into remarks field (initialize if needed)
  if (!item.remarks) {
    item.remarks = '';
  }

  // Remove existing "Used By" section if it exists (do this BEFORE checking if we have new references)
  if (item.remarks.includes('#### Used by')) {
    // Remove the entire "Used By" section (from "#### Used by" to the next "####" or end)
    item.remarks = item.remarks.replace(/\n*#### Used by\n[\s\S]*?(?=\n####|\n*$)/g, '');
  }

  // Filter to only include references that exist in the current package/version
  // Also include cross-product references with Common API
  let filteredReferences = references.filter(ref => {
    // Include if the reference exists in current version
    if (availableUIDs.has(ref.uid)) {
      return true;
    }

    // Check for cross-product references with Common API
    const refPackage = ref.uid.split('!')[0];
    const isCommonApiRef = ['office', 'office-runtime'].includes(refPackage);
    const isCurrentCommonApi = ['office', 'office-runtime'].includes(currentPackage);

    // Common API files should show references from ALL products
    if (isCurrentCommonApi) {
      return true;
    }

    // Product-specific files should show references from Common API
    if (isCommonApiRef) {
      return commonApiUIDs.has(ref.uid);
    }

    return false;
  });

  // Extract the class name from the current item's UID
  // Example: "excel!Excel.AllowEditRange:class" → "Excel.AllowEditRange"
  const uidParts = item.uid.split('!');
  if (uidParts.length === 2) {
    const reference = uidParts[1];
    const currentClassName = reference.split(':')[0].split('#')[0];

    // Filter out self-references (references from the same class)
    filteredReferences = filteredReferences.filter(ref => {
      const lastDotIndex = ref.name.lastIndexOf('.');
      const refClassName = lastDotIndex > 0 ? ref.name.substring(0, lastDotIndex) : ref.name;
      return refClassName !== currentClassName;
    });
  }

  // If no valid references remain after filtering, we're done (old section already removed)
  if (filteredReferences.length === 0) {
    return true; // Return true because we removed the old section
  }

  // Deduplicate method overloads
  const deduplicated = deduplicateMethodOverloads(filteredReferences);

  // Generate the "Used By" markdown section
  const usedBySection = generateUsedBySection(deduplicated);

  // Insert before "#### Examples" if it exists, otherwise append
  if (item.remarks.includes('#### Examples')) {
    item.remarks = item.remarks.replace('#### Examples', usedBySection + '\n#### Examples');
  } else if (item.remarks.trim()) {
    item.remarks += usedBySection;
  } else {
    item.remarks = usedBySection.substring(2); // Remove leading \n\n
  }

  return true;
}

/**
 * Deduplicates method overloads by keeping only the first overload.
 * Preserves the original UID with overload suffix for valid xref links.
 */
function deduplicateMethodOverloads(references: UsedByReference[]): UsedByReference[] {
  const seen = new Set<string>();
  const result: UsedByReference[] = [];

  for (const ref of references) {
    // Get base UID for deduplication: ":member(1)" -> ":member"
    const baseUID = ref.uid.replace(/\(\d+\)$/, '');

    if (!seen.has(baseUID)) {
      seen.add(baseUID);
      // Keep the original UID with overload suffix for valid xref links
      result.push(ref);
    }
  }

  return result;
}

/**
 * Converts a UID to a URL for use in markdown links.
 * Example: excel!Excel.DataPivotHierarchy#summarizeBy:member
 * -> /javascript/api/excel/excel.datapivothierarchy#summarizeby-member
 */
function convertUidToUrl(uid: string): string {
  // Extract overload suffix like (1), (2) to append at the end
  const overloadMatch = uid.match(/\((\d+)\)$/);
  const overloadSuffix = overloadMatch ? `(${overloadMatch[1]})` : '';
  const cleanUid = uid.replace(/\(\d+\)$/, '');

  // Split on ! to get package and reference
  const parts = cleanUid.split('!');
  if (parts.length !== 2) {
    return '';
  }

  const packageName = parts[0];
  let reference = parts[1];

  // Split reference into class path and member part
  // Instance members use #: "Excel.DataPivotHierarchy#summarizeBy:member"
  // Static members use .: "Excel.CustomFunctionManager.newObject:member"
  let classPath: string;
  let memberPart: string;

  const hashIndex = reference.indexOf('#');

  if (hashIndex > 0) {
    // Instance member (uses #)
    classPath = reference.substring(0, hashIndex);
    memberPart = reference.substring(hashIndex + 1);
  } else {
    // Check if this is a static member (has : but no #)
    const colonIndex = reference.indexOf(':');
    if (colonIndex > 0) {
      // Static member - find the last . before the :
      const beforeColon = reference.substring(0, colonIndex);
      const lastDotIndex = beforeColon.lastIndexOf('.');

      if (lastDotIndex > 0) {
        classPath = reference.substring(0, lastDotIndex);
        memberPart = reference.substring(lastDotIndex + 1);
      } else {
        // No dot found, treat entire thing as class path
        classPath = reference;
        memberPart = '';
      }
    } else {
      // No # and no :, so it's just a class/interface reference
      classPath = reference;
      memberPart = '';
    }
  }

  // Convert class path to lowercase for URL
  const classPathLower = classPath.toLowerCase();

  // Build anchor: <package>-<full-qualified-path-with-dashes>-<member-name>-<kind>
  let anchor = '';
  if (memberPart) {
    // Convert everything to lowercase and replace : with - and dots with - for the anchor
    const anchorBase = `${packageName}-${classPath.replace(/\./g, '-')}-${memberPart.replace(/:/g, '-')}`.toLowerCase();
    anchor = `#${anchorBase}${overloadSuffix}`;
  }

  // For namespace references (with or without members), don't duplicate the namespace name in the path
  // Examples:
  //   excel!Excel:namespace -> /javascript/api/excel
  //   excel!Excel.run:function(1) -> /javascript/api/excel#excel-excel-run-function(1)
  //   office-runtime!OfficeRuntime.displayWebDialog:function -> /javascript/api/office-runtime#...
  //   excel!Excel.Worksheet.getRange:method -> /javascript/api/excel/excel.worksheet#...
  // Normalize by removing hyphens for comparison (e.g., office-runtime vs OfficeRuntime)
  const normalizedClassPath = classPathLower.replace(/-/g, '');
  const normalizedPackage = packageName.toLowerCase().replace(/-/g, '');
  const isNamespace = normalizedClassPath === normalizedPackage;

  if (isNamespace) {
    return `/javascript/api/${packageName}${anchor}`;
  }

  // Build URL: /javascript/api/<package>/<class-path><anchor>
  return `/javascript/api/${packageName}/${classPathLower}${anchor}`;
}

/**
 * Generates the markdown for the "Used By" section.
 * Groups references by containing class with inline member lists.
 */
function generateUsedBySection(references: UsedByReference[]): string {
  if (references.length === 0) {
    return '';
  }

  // Filter out references from the Interfaces namespace
  // (e.g., Excel.Interfaces.DataValidationData, Excel.Interfaces.DataValidationUpdateData)
  const filteredReferences = references.filter(ref => !ref.name.includes('.Interfaces.'));

  if (filteredReferences.length === 0) {
    return '';
  }

  const lines: string[] = ['\n\n#### Used by\n'];

  // Group by containing class
  const groupedByClass = groupByContainingClass(filteredReferences);

  // Sort class names alphabetically
  const classNames = Object.keys(groupedByClass).sort();

  for (const className of classNames) {
    const members = groupedByClass[className];

    // Sort members alphabetically by member name (without class prefix)
    members.sort((a, b) => {
      const memberA = a.name.substring(className.length + 1); // Remove "ClassName." prefix
      const memberB = b.name.substring(className.length + 1);
      return memberA.localeCompare(memberB);
    });

    // Build inline member list with links
    const memberLinks: string[] = [];
    let classUrl = '';
    for (const ref of members) {
      const url = convertUidToUrl(ref.uid);
      const memberName = ref.name.substring(className.length + 1); // Remove "ClassName." prefix
      memberLinks.push(`[${memberName}](${url})`);

      // Extract package and build class URL from first member's UID
      if (!classUrl) {
        const uidParts = ref.uid.split('!');
        if (uidParts.length === 2) {
          const packageName = uidParts[0];
          const classPathLower = className.toLowerCase();

          // For namespace-only references (e.g., Excel, Office, OfficeRuntime), don't duplicate the namespace name
          // URL should be /javascript/api/excel, not /javascript/api/excel/excel
          // Normalize by removing hyphens for comparison (e.g., office-runtime vs OfficeRuntime)
          const normalizedClassPath = classPathLower.replace(/-/g, '');
          const normalizedPackage = packageName.toLowerCase().replace(/-/g, '');
          const isNamespaceOnly = normalizedClassPath === normalizedPackage;

          if (isNamespaceOnly) {
            classUrl = `/javascript/api/${packageName}`;
          } else {
            classUrl = `/javascript/api/${packageName}/${classPathLower}`;
          }
        }
      }
    }

    // Format as: - [ClassName](url): member1, member2, member3
    const classLink = classUrl ? `[${className}](${classUrl})` : className;
    lines.push(`- ${classLink}: ${memberLinks.join(', ')}`);
  }

  return lines.join('\n');
}

/**
 * Groups references by package name.
 */
/**
 * Groups references by their containing class.
 * Example: "Excel.Worksheet.getRange" -> class is "Excel.Worksheet"
 */
function groupByContainingClass(references: UsedByReference[]): Record<string, UsedByReference[]> {
  const grouped: Record<string, UsedByReference[]> = {};

  for (const ref of references) {
    // Extract class name from the full qualified name
    // E.g., "Excel.Worksheet.getRange" -> "Excel.Worksheet"
    const lastDotIndex = ref.name.lastIndexOf('.');
    const className = lastDotIndex > 0 ? ref.name.substring(0, lastDotIndex) : ref.name;

    if (!grouped[className]) {
      grouped[className] = [];
    }
    grouped[className].push(ref);
  }

  return grouped;
}

// ---- Main Processing ----

async function main(): Promise<void> {
  console.log('\n=== Office YAML Post-Processor ===\n');

  // Build the "Used By" index from all JSON files
  console.log('Building "Used By" index from JSON files...');
  const usedByIndex = buildUsedByIndex();
  const indexSize = Object.keys(usedByIndex).length;
  console.log(`✓ Built index with ${indexSize} referenced types\n`);

  // Build a global set of UIDs from Common APIs for cross-product references
  console.log('Building Common API UID index...');
  const commonApiUIDs = new Set<string>();
  for (const commonFolder of ['office', 'office_release', 'office-runtime']) {
    const folderPath = path.join(YAML_BASE_PATH, commonFolder);
    if (fsx.existsSync(folderPath)) {
      const uids = buildAvailableUIDs(folderPath);
      uids.forEach(uid => commonApiUIDs.add(uid));
    }
  }
  console.log(`✓ Built Common API index with ${commonApiUIDs.size} UIDs\n`);

  let totalFiles = 0;
  let totalFolders = 0;

  for (const folder of PRODUCT_FOLDERS) {
    const result = await processFolderIfExists(folder, usedByIndex, commonApiUIDs);
    if (result) {
      totalFiles += result.filesProcessed;
      totalFolders++;
    }
  }

  console.log(`\n✓ Office YAML processing complete`);
  console.log(`  Processed ${totalFiles} files across ${totalFolders} folders\n`);
}

function shouldReportUnusedSnippets(folderName: string): boolean {
  // Only report unused snippets for main/preview versions
  // Skip versioned folders (e.g., excel_1_1, word_1_2, outlook_1_3)
  // Skip platform-specific folders (e.g., excel_online, word_desktop_1_1)

  // Pattern: folder_number or folder_platform or folder_number_hidden
  const versionedPattern = /_\d+(_\d+)?(_hidden)?(_document)?$/;
  const platformPattern = /_(online|desktop|release|preview)(_\d+(_\d+)?)?$/;

  if (versionedPattern.test(folderName) || platformPattern.test(folderName)) {
    return false;
  }

  return true;
}

/**
 * Builds a set of all UIDs that exist in the given folder.
 * This is used to filter "Used By" references to only include APIs that exist in the current version.
 */
function buildAvailableUIDs(folderPath: string): Set<string> {
  const uids = new Set<string>();
  const yamlFiles = findYamlFiles(folderPath);

  for (const filePath of yamlFiles) {
    try {
      const content = fsx.readFileSync(filePath, 'utf-8');
      const doc: any = yaml.load(content);

      if (doc && typeof doc === 'object') {
        // Add main item UID
        if (doc.uid) {
          uids.add(doc.uid);
        }

        // Add nested item UIDs from arrays
        const arrayNames = ['properties', 'methods', 'events', 'functions', 'fields', 'typeParameters'];
        for (const arrayName of arrayNames) {
          if (Array.isArray(doc[arrayName])) {
            for (const item of doc[arrayName]) {
              if (item && item.uid) {
                uids.add(item.uid);
              }
            }
          }
        }
      }
    } catch (error) {
      // Skip files that can't be parsed
    }
  }

  return uids;
}

async function processFolderIfExists(
  folderName: string,
  usedByIndex: UsedByIndex,
  commonApiUIDs: Set<string>
): Promise<{ filesProcessed: number } | null> {
  const folderPath = path.join(YAML_BASE_PATH, folderName);

  if (!fsx.existsSync(folderPath)) {
    return null;
  }

  console.log(`Processing ${folderName}...`);

  const snippets = loadSnippets(folderName);
  const snippetsAll = new Map(snippets);
  const usedSnippets = new Set<string>();

  // Build set of UIDs available in this folder to filter "Used By" references
  const availableUIDs = buildAvailableUIDs(folderPath);

  // Get the package name for cross-product reference filtering
  const currentPackage = getBaseProductName(folderName);

  const yamlFiles = findYamlFiles(folderPath);

  for (const filePath of yamlFiles) {
    await processYamlFile(filePath, snippetsAll, usedSnippets, usedByIndex, availableUIDs, commonApiUIDs, currentPackage);
  }

  // Only report unused snippets for preview/main versions, not versioned subsets
  if (shouldReportUnusedSnippets(folderName)) {
    reportUnusedSnippets(snippets, usedSnippets, folderName);
  }

  return { filesProcessed: yamlFiles.length };
}

function loadSnippets(folderName: string): Map<string, string[]> {
  // Try versioned snippets first, fallback to main snippets.yaml
  const versionedPath = path.join(JSON_BASE_PATH, folderName, 'snippets.yaml');
  const mainPath = path.join(JSON_BASE_PATH, 'snippets.yaml');

  let snippetsPath: string;
  if (fsx.existsSync(versionedPath)) {
    snippetsPath = versionedPath;
  } else if (fsx.existsSync(mainPath)) {
    snippetsPath = mainPath;
  } else {
    return new Map();
  }

  const content = fsx.readFileSync(snippetsPath, 'utf-8');
  const obj = yaml.load(content) as ISnippetsFile;

  return new Map(Object.entries(obj));
}

function findYamlFiles(dirPath: string): string[] {
  const files: string[] = [];

  function walk(currentPath: string): void {
    const entries = fsx.readdirSync(currentPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name.endsWith('.yml')) {
        files.push(fullPath);
      }
    }
  }

  walk(dirPath);
  return files;
}

async function processYamlFile(
  filePath: string,
  snippets: Map<string, string[]>,
  usedSnippets: Set<string>,
  usedByIndex: UsedByIndex,
  availableUIDs: Set<string>,
  commonApiUIDs: Set<string>,
  currentPackage: string
): Promise<void> {
  const content = fsx.readFileSync(filePath, 'utf-8');

  // Preserve the YamlMime header if present
  const lines = content.split('\n');
  const yamlMimeHeader = lines[0].startsWith('### YamlMime:') ? lines[0] + '\n' : '';

  let doc: any;

  try {
    doc = yaml.load(content);
  } catch (error) {
    console.warn(`  Warning: Failed to parse ${filePath}: ${error}`);
    return;
  }

  if (!doc || typeof doc !== 'object') {
    return;
  }

  let modified = false;

  // Process main item
  if (doc.uid) {
    modified = injectExamples(doc, snippets, usedSnippets) || modified;
    modified = hyperlinkApiSets(doc) || modified;
    modified = injectUsedBySection(doc, usedByIndex, availableUIDs, commonApiUIDs, currentPackage) || modified;
  }

  // Process nested items in arrays
  // Note: 'fields' (enum members) are excluded from Used By injection because OPS doesn't support remarks on enum fields
  const arrayNames = ['properties', 'methods', 'events', 'functions', 'fields', 'typeParameters'];
  for (const arrayName of arrayNames) {
    if (Array.isArray(doc[arrayName])) {
      for (const item of doc[arrayName]) {
        if (item && item.uid) {
          modified = injectExamples(item, snippets, usedSnippets) || modified;
          modified = hyperlinkApiSets(item) || modified;
          // Skip Used By injection for enum fields - OPS doesn't support remarks on enum fields
          if (arrayName !== 'fields') {
            modified = injectUsedBySection(item, usedByIndex, availableUIDs, commonApiUIDs, currentPackage) || modified;
          }
        }
      }
    }
  }

  if (modified) {
    let output = yaml.dump(doc, {
      lineWidth: -1,
      noRefs: true,
      sortKeys: false,
      noCompatMode: true,
      flowLevel: -1
    });

    // Fix YAML formatting issue: yaml.dump() sometimes puts markdown list bullets on separate lines
    // Convert "  -\n  [Text](url)" to "  - [Text](url)"
    const lines = output.split('\n');
    const linesToRemove = new Set<number>();

    for (let i = 0; i < lines.length - 1; i++) {
      // Check if current line ends with just a bullet and next line starts with a markdown link
      const currentMatch = lines[i].match(/^(\s+)-$/);
      if (currentMatch && lines[i + 1].match(/^\s+\[.+?\]\(.+?\)/)) {
        const indent = currentMatch[1];
        const nextLineContent = lines[i + 1].trim();
        lines[i] = `${indent}- ${nextLineContent}`;
        linesToRemove.add(i + 1); // Mark next line for removal
      }
    }

    // Fix inline class member lists: join "ClassName:" with member links on next line
    // Convert "  - ClassName:\n  [member](url)" to "  - ClassName: [member](url)"
    for (let i = 0; i < lines.length - 1; i++) {
      if (linesToRemove.has(i)) continue; // Skip already removed lines

      // Check if current line ends with ":" and next line has markdown links
      const colonMatch = lines[i].match(/^(\s+- .+):$/);
      if (colonMatch && lines[i + 1].match(/^\s+\[.+?\]\(.+?\)/)) {
        // Join the lines with a space
        lines[i] = `${lines[i]} ${lines[i + 1].trim()}`;
        linesToRemove.add(i + 1);
      }
    }

    // Join continuation lines for inline member lists
    // When a line ends with a comma and next line starts with markdown link, join them
    for (let i = 0; i < lines.length; i++) {
      if (linesToRemove.has(i)) continue;

      // If this line ends with a comma, join all continuation lines
      if (lines[i].match(/,\s*$/)) {
        let j = i + 1;
        // Keep joining continuation lines while they exist
        while (j < lines.length && !linesToRemove.has(j) && lines[j].match(/^\s+\[.+?\]\(.+?\)/)) {
          lines[i] = `${lines[i]} ${lines[j].trim()}`;
          linesToRemove.add(j);
          j++;
          // If the line no longer ends with comma, we're done
          if (!lines[i].match(/,\s*$/)) break;
        }
      }
    }

    output = lines.filter((_, index) => !linesToRemove.has(index)).join('\n');

    // Prepend the YamlMime header if it existed
    if (yamlMimeHeader) {
      output = yamlMimeHeader + output;
    }

    fsx.writeFileSync(filePath, output, 'utf-8');
  }
}

function injectExamples(
  item: IYamlItem,
  snippets: Map<string, string[]>,
  usedSnippets: Set<string>
): boolean {
  if (!item.uid) {
    return false;
  }

  // Remove package prefix: "excel!Excel.Range#clear:member(1)" -> "Excel.Range#clear:member(1)"
  const nameWithoutPackage = item.uid.replace(/^[^.]+\!/, '');
  const snippetCode = snippets.get(nameWithoutPackage);

  if (!snippetCode || snippetCode.length === 0) {
    return false;
  }

  usedSnippets.add(nameWithoutPackage);

  // Generate example text
  const examplesSection = generateExampleSnippetText(snippetCode);

  // Check if examples already exist
  if (item.remarks?.includes('#### Examples') ||
      item.syntax?.return?.description?.includes('#### Examples')) {
    return false;
  }

  // Inject into remarks (preferred) or syntax.return.description (fallback)
  // Only use remarks if it has actual content (not just whitespace)
  if (item.remarks && item.remarks.trim()) {
    item.remarks += examplesSection;
    return true;
  } else if (item.syntax?.return) {
    // Prefer return.description over creating empty remarks
    if (!item.syntax.return.description) {
      item.syntax.return.description = '';
    }
    item.syntax.return.description += examplesSection;
    return true;
  } else {
    // Only create new remarks as last resort
    item.remarks = examplesSection.substring(2); // Remove leading \n\n
    return true;
  }

  return false;
}

function generateExampleSnippetText(snippets: string[]): string {
  const text: string[] = ['\n\n#### Examples\n'];
  for (const snippet of snippets) {
    text.push(`\`\`\`TypeScript\n${snippet}\n\`\`\``);
  }
  return text.join('\n');
}

function hyperlinkApiSets(item: IYamlItem): boolean {
  if (!item.uid) {
    return false;
  }

  let modified = false;
  const url = getApiSetUrl(item.uid);

  if (item.summary && typeof item.summary === 'string') {
    // First capitalize "Api" to "API"
    let newSummary = item.summary.replace(/Api set:/g, 'API set:');
    // Then add hyperlink: \[API set: ExcelApi 1.1\] -> [API set: ExcelApi 1.1](url)
    newSummary = newSummary.replace(/\\\[(API set:[^\]]+)\\\]/g, (match, apiSetText) => {
      return `[${apiSetText}](${url})`;
    });

    if (newSummary !== item.summary) {
      item.summary = newSummary;
      modified = true;
    }
  }

  if (item.remarks && typeof item.remarks === 'string') {
    // First capitalize "Api" to "API"
    let newRemarks = item.remarks.replace(/Api set:/g, 'API set:');
    // Then add hyperlink: \[API set: ExcelApi 1.1\] -> [API set: ExcelApi 1.1](url)
    newRemarks = newRemarks.replace(/\\\[(API set:[^\]]+)\\\]/g, (match, apiSetText) => {
      return `[${apiSetText}](${url})`;
    });

    if (newRemarks !== item.remarks) {
      item.remarks = newRemarks;
      modified = true;
    }
  }

  return modified;
}

function getApiSetUrl(uid: string): string {
  if (!uid) {
    return REQUIREMENT_SET_URLS.default;
  }

  // Extract package name from UID (e.g., "onenote!OneNote.InkWord:class" -> "onenote")
  // This prevents false matches like "word" matching in "InkWord"
  const packageMatch = uid.match(/^([^!]+)!/);
  if (!packageMatch) {
    return REQUIREMENT_SET_URLS.default;
  }

  const packageName = packageMatch[1].toLowerCase();

  // Check if the package name matches any known product
  if (REQUIREMENT_SET_URLS[packageName]) {
    return REQUIREMENT_SET_URLS[packageName];
  }

  return REQUIREMENT_SET_URLS.default;
}

function reportUnusedSnippets(
  snippets: Map<string, string[]>,
  usedSnippets: Set<string>,
  folderName: string
): void {
  const unused = Array.from(snippets.keys()).filter(k => !usedSnippets.has(k));

  if (unused.length > 0) {
    console.log();
    for (const apiName of unused) {
      console.warn(`Warning: Unused snippet ${apiName}`);
    }
  }
}

// ---- Entry Point ----

main().catch((error) => {
  console.error('\n✗ Error during Office YAML processing:');
  console.error(error);
  process.exit(1);
});
